/*
 * Copyright (c) 2014, 2015, Project Toothbytes. All rights reserved.
 *
 *
*/
package window.forms;

import java.awt.Color;
import java.awt.Dialog;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import utilities.AdditionalInfo;
import utilities.MedicalCond;
import utilities.PersonalInfo;

public class MedicalCondition extends javax.swing.JPanel {
    public JDialog tb;
    public PersonalInfo pi;
    public AdditionalInfo ai;
    public MedicalCond mc;
    
    public MedicalCondition(JDialog tb, PersonalInfo pi, AdditionalInfo ai) {
        initComponents();
        q1Yes.setActionCommand("y");
        q1No.setActionCommand("n");
        q2Yes.setActionCommand("y");
        q2No.setActionCommand("n");
        q3Yes.setActionCommand("y");
        q3No.setActionCommand("n");
        q4Yes.setActionCommand("y");
        q4No.setActionCommand("n");
        q5Yes.setActionCommand("y");
        q5No.setActionCommand("n");
        q6Yes.setActionCommand("y");
        q6No.setActionCommand("n");
        q7Yes.setActionCommand("y");
        q7No.setActionCommand("n");
        q8Yes.setActionCommand("y");
        q8No.setActionCommand("n");
        q9Yes.setActionCommand("y");
        q9No.setActionCommand("n");
        q10Yes.setActionCommand("y");
        q10No.setActionCommand("n");
        
        this.tb = tb;
        this.pi = pi;
        this.ai = ai;
    }
    
    private final String BUTTON_DIR = "res/buttons/";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q1 = new javax.swing.ButtonGroup();
        q2 = new javax.swing.ButtonGroup();
        q3 = new javax.swing.ButtonGroup();
        q4 = new javax.swing.ButtonGroup();
        q5 = new javax.swing.ButtonGroup();
        q6 = new javax.swing.ButtonGroup();
        q7 = new javax.swing.ButtonGroup();
        q8 = new javax.swing.ButtonGroup();
        q9 = new javax.swing.ButtonGroup();
        q10 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        q1Label = new javax.swing.JLabel();
        q2Label = new javax.swing.JLabel();
        q3Label = new javax.swing.JLabel();
        q4Label = new javax.swing.JLabel();
        q5Label = new javax.swing.JLabel();
        q6Label = new javax.swing.JLabel();
        q7Label = new javax.swing.JLabel();
        q8Label = new javax.swing.JLabel();
        q9Label = new javax.swing.JLabel();
        q10Label = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        q11CB1 = new javax.swing.JCheckBox();
        q11CB2 = new javax.swing.JCheckBox();
        q11CB3 = new javax.swing.JCheckBox();
        q11CB4 = new javax.swing.JCheckBox();
        q11CB4TF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        q12opt1 = new javax.swing.JCheckBox();
        q12opt2 = new javax.swing.JCheckBox();
        q12opt3 = new javax.swing.JCheckBox();
        q12opt4 = new javax.swing.JCheckBox();
        q12opt5 = new javax.swing.JCheckBox();
        q12opt6 = new javax.swing.JCheckBox();
        q12opt7 = new javax.swing.JCheckBox();
        q12opt8 = new javax.swing.JCheckBox();
        q12opt9 = new javax.swing.JCheckBox();
        q12opt10 = new javax.swing.JCheckBox();
        q12opt11 = new javax.swing.JCheckBox();
        q12opt12 = new javax.swing.JCheckBox();
        q12opt13 = new javax.swing.JCheckBox();
        q12opt14 = new javax.swing.JCheckBox();
        q12opt15 = new javax.swing.JCheckBox();
        finishButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        q1No = new javax.swing.JRadioButton();
        q1Yes = new javax.swing.JRadioButton();
        q2Yes = new javax.swing.JRadioButton();
        q2YesTF = new javax.swing.JTextField();
        q2No = new javax.swing.JRadioButton();
        q3Yes = new javax.swing.JRadioButton();
        q3No = new javax.swing.JRadioButton();
        q3YesTF = new javax.swing.JTextField();
        q4Yes = new javax.swing.JRadioButton();
        q4YesTF = new javax.swing.JTextField();
        q4No = new javax.swing.JRadioButton();
        q5Yes = new javax.swing.JRadioButton();
        q5YesTF = new javax.swing.JTextField();
        q5No = new javax.swing.JRadioButton();
        q6Yes = new javax.swing.JRadioButton();
        q6No = new javax.swing.JRadioButton();
        q7Yes = new javax.swing.JRadioButton();
        q7No = new javax.swing.JRadioButton();
        q8Yes = new javax.swing.JRadioButton();
        q8No = new javax.swing.JRadioButton();
        q9Yes = new javax.swing.JRadioButton();
        q9No = new javax.swing.JRadioButton();
        q10Yes = new javax.swing.JRadioButton();
        q10No = new javax.swing.JRadioButton();
        bloodPressureTF = new javax.swing.JTextField();
        bloodTypeCB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Medical Condition");

        q1Label.setText("Are you in good health?");

        q2Label.setText("Are you under medical treatment now?");

        q3Label.setText("Have you ever had serious illness or surgical operation?");

        q4Label.setText("Have you ever been hospitalized?");

        q5Label.setText("Are you taking any prescription/ non-prescribed medication?");

        q6Label.setText("Do you use tobacco products?");

        q7Label.setText("Do you use alcohol or any other drugs?");

        q8Label.setText("Are you pregnant?");

        q9Label.setText("Are you nursing?");

        q10Label.setText("Are you taking birth control pills?");

        jLabel12.setText("Are you allergic to any of the following?");

        q11CB1.setText("Local Anesthetic(ex. Lidocaine)");

        q11CB2.setText("Penicilin, Antibiotics");

        q11CB3.setText("Aspirin");

        q11CB4.setText("Others");
        q11CB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q11CB4ActionPerformed(evt);
            }
        });

        q11CB4TF.setEditable(false);

        jLabel13.setText("Blood type");

        jLabel14.setText("Blood pressure");

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Do you have any of the following?"));

        q12opt1.setText("High Blood Pressure");

        q12opt2.setText("Low Blood Pressure");

        q12opt3.setText("Epilepsy / Convulsion");

        q12opt4.setText("AIDS / HIV");

        q12opt5.setText("Sexually Transmitted Disease");

        q12opt6.setText("Stomach Troubles/ Ulcer");

        q12opt7.setText("Fainting Seizures");

        q12opt8.setText("Rapid Weight Loss");

        q12opt9.setText("Radiation Theraphy");

        q12opt10.setText("Joint Replacement / Implant");

        q12opt11.setText("Heart Disease");

        q12opt12.setText("Hepatitis");

        q12opt13.setText("Cancer / Tumors");

        q12opt14.setText("Asthma");

        q12opt15.setText("Heart Attacks");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(q12opt1)
                            .addGap(89, 89, 89)
                            .addComponent(q12opt6))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(q12opt4)
                                .addComponent(q12opt3)
                                .addComponent(q12opt2))
                            .addGap(83, 83, 83)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(q12opt9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(q12opt8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(q12opt7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(60, 60, 60)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(q12opt5)
                        .addGap(45, 45, 45)
                        .addComponent(q12opt10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q12opt15)
                    .addComponent(q12opt11)
                    .addComponent(q12opt12)
                    .addComponent(q12opt13)
                    .addComponent(q12opt14))
                .addGap(123, 123, 123))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q12opt1)
                    .addComponent(q12opt6)
                    .addComponent(q12opt11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q12opt2)
                    .addComponent(q12opt7)
                    .addComponent(q12opt12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q12opt3)
                    .addComponent(q12opt8)
                    .addComponent(q12opt13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q12opt4)
                    .addComponent(q12opt9)
                    .addComponent(q12opt14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q12opt5)
                    .addComponent(q12opt10)
                    .addComponent(q12opt15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        finishButton.setIcon(new javax.swing.ImageIcon(BUTTON_DIR+"Save.png"));
        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(BUTTON_DIR+"Back.png"));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(BUTTON_DIR+"Cancel.png"));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        q1.add(q1No);
        q1No.setText("No");

        q1.add(q1Yes);
        q1Yes.setText("Yes");

        q2.add(q2Yes);
        q2Yes.setText("Yes,");
        q2Yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q2YesMouseClicked(evt);
            }
        });

        q2YesTF.setEditable(false);
        q2YesTF.setBackground(new java.awt.Color(250, 250, 250));
        q2YesTF.setText("name of condition being treated");

        q2.add(q2No);
        q2No.setText("No");
        q2No.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q2NoMouseClicked(evt);
            }
        });

        q3.add(q3Yes);
        q3Yes.setText("Yes");
        q3Yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q3YesMouseClicked(evt);
            }
        });

        q3.add(q3No);
        q3No.setText("No");
        q3No.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q3NoMouseClicked(evt);
            }
        });

        q3YesTF.setEditable(false);
        q3YesTF.setBackground(new java.awt.Color(250, 250, 250));
        q3YesTF.setText("name of illness / operation");

        q4.add(q4Yes);
        q4Yes.setText("Yes");
        q4Yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q4YesMouseClicked(evt);
            }
        });

        q4YesTF.setEditable(false);
        q4YesTF.setBackground(new java.awt.Color(250, 250, 250));
        q4YesTF.setText("when and why");

        q4.add(q4No);
        q4No.setText("No");
        q4No.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q4NoMouseClicked(evt);
            }
        });

        q5.add(q5Yes);
        q5Yes.setText("Yes");
        q5Yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q5YesMouseClicked(evt);
            }
        });

        q5YesTF.setEditable(false);
        q5YesTF.setBackground(new java.awt.Color(250, 250, 250));
        q5YesTF.setText("specify medication");

        q5.add(q5No);
        q5No.setText("No");
        q5No.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q5NoMouseClicked(evt);
            }
        });

        q6.add(q6Yes);
        q6Yes.setText("Yes");

        q6.add(q6No);
        q6No.setText("No");

        q7.add(q7Yes);
        q7Yes.setText("Yes");

        q7.add(q7No);
        q7No.setText("No");

        q8.add(q8Yes);
        q8Yes.setText("Yes");

        q8.add(q8No);
        q8No.setText("No");

        q9.add(q9Yes);
        q9Yes.setText("Yes");

        q9.add(q9No);
        q9No.setText("No");

        q10.add(q10Yes);
        q10Yes.setText("Yes");

        q10.add(q10No);
        q10No.setText("No");

        bloodPressureTF.setText("000/000");

        bloodTypeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Blood Type", "A", "A-", "A+", "B", "B-", "B+", "O", "O-", "O+", "AB", "AB-", "AB+" }));
        bloodTypeCB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*");

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*");

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(q11CB1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bloodTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q11CB2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bloodPressureTF, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(q8Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(q7Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(q6Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(q5Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                            .addComponent(q4Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(q3Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(q2Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(q1Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(q9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(q7Yes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(q7No))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(q5Yes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(q5YesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(q5No))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(q4Yes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(q4YesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(q4No))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(q1Yes)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(q1No))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(q3Yes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(q2Yes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(q3YesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(q3No))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(q2YesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(q2No))))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(q6Yes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(q6No)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(q8Yes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(q8No))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(q9Yes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(q9No))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(q10Yes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(q10No))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q11CB4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q11CB4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(q11CB3))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finishButton)))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1Label)
                    .addComponent(q1No)
                    .addComponent(q1Yes)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2Label)
                    .addComponent(q2Yes)
                    .addComponent(q2YesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q2No)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3Label)
                    .addComponent(q3Yes)
                    .addComponent(q3No)
                    .addComponent(q3YesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4Label)
                    .addComponent(q4Yes)
                    .addComponent(q4No)
                    .addComponent(q4YesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5Label)
                    .addComponent(q5Yes)
                    .addComponent(q5No)
                    .addComponent(q5YesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q6Label)
                    .addComponent(q6Yes)
                    .addComponent(q6No)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q7Label)
                    .addComponent(q7Yes)
                    .addComponent(q7No)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q8Label)
                    .addComponent(q8Yes)
                    .addComponent(q8No)
                    .addComponent(jLabel9))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q9Label)
                    .addComponent(q9Yes)
                    .addComponent(q9No)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q10Label)
                    .addComponent(q10Yes)
                    .addComponent(q10No)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q11CB1)
                    .addComponent(q11CB2)
                    .addComponent(q11CB3)
                    .addComponent(q11CB4)
                    .addComponent(q11CB4TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(bloodPressureTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishButton)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void q2NoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q2NoMouseClicked
        q2YesTF.setEditable(false);
        q2YesTF.setBackground(Color.red); // To be removed
    }//GEN-LAST:event_q2NoMouseClicked

    private void q2YesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q2YesMouseClicked
        q2YesTF.setEditable(true);
        q2YesTF.setText("");
        q2YesTF.setBackground(Color.green); // To be removed  
    }//GEN-LAST:event_q2YesMouseClicked

    private void q11CB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q11CB4ActionPerformed
        if(q11CB4.isSelected() == true){
            q11CB4TF.setEditable(true);
            q11CB4TF.setBackground(Color.green); // To be removed
        }else{
            q11CB4TF.setEditable(false);
            q11CB4TF.setBackground(Color.red);
            q11CB4TF.setText("");
        }
    }//GEN-LAST:event_q11CB4ActionPerformed

    private void q3YesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q3YesMouseClicked
        q3YesTF.setEditable(true);
        q3YesTF.setText("");
        q3YesTF.setBackground(Color.green); // To be removed 
    }//GEN-LAST:event_q3YesMouseClicked

    private void q4YesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q4YesMouseClicked
        q4YesTF.setEditable(true);
        q4YesTF.setText("");
        q4YesTF.setBackground(Color.green); // To be removed 
    }//GEN-LAST:event_q4YesMouseClicked

    private void q5YesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q5YesMouseClicked
        q5YesTF.setEditable(true);
        q5YesTF.setText("");
        q5YesTF.setBackground(Color.green); // To be removed 
    }//GEN-LAST:event_q5YesMouseClicked

    private void q3NoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q3NoMouseClicked
        q3YesTF.setEditable(false);
        q3YesTF.setBackground(Color.red); // To be removed
    }//GEN-LAST:event_q3NoMouseClicked

    private void q4NoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q4NoMouseClicked
        q4YesTF.setEditable(false);
        q4YesTF.setBackground(Color.red); // To be removed
    }//GEN-LAST:event_q4NoMouseClicked

    private void q5NoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q5NoMouseClicked
        q5YesTF.setEditable(false);
        q5YesTF.setBackground(Color.red); // To be removed
    }//GEN-LAST:event_q5NoMouseClicked

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        grayTFBorders();
        if(entriesValid()) {
            String q2ansTF ="No";
            String q3ansTF ="No";
            String q4ansTF ="No";
            String q5ansTF ="No";
            
            String q1ans = getAnswer(q1);
            
            if(getAnswer(q2).equalsIgnoreCase("Yes")) {
                q2ansTF = q2YesTF.getText();
            }
            
            if(getAnswer(q3).equalsIgnoreCase("Yes")) {
                    q3ansTF = q3YesTF.getText();
            }
            
            if(getAnswer(q4).equalsIgnoreCase("Yes")) {
                q4ansTF = q4YesTF.getText();
            }
            
            if(getAnswer(q5).equalsIgnoreCase("Yes")){
                q5ansTF = q5YesTF.getText();
            }
            
            String q6ans = getAnswer(q6);
            String q7ans = getAnswer(q7);
            String q8ans = getAnswer(q8);
            String q9ans = getAnswer(q9);
            String q10ans = getAnswer(q10);
            
            String sq11 = "";
            
            if(q11CB1.isSelected()){
                sq11 = "Local Anesthetic ";
            } else if (q11CB2.isSelected()){
                sq11 = sq11 + "Penicillin, Antibiotics ";
            } else if (q11CB3.isSelected()){
                sq11 = sq11 + "Aspirin ";
            } else if (q11CB4.isSelected()){
                sq11 = sq11 + q11CB4TF.getText();
            }
            
            String bloodType = null;
            if(bloodTypeCB.getSelectedIndex() != 0){
                bloodType = bloodTypeCB.getSelectedItem().toString();
            }
            
            String bloodPressure = bloodPressureTF.getText();
            
            String sq12 = "";
            
            if(q12opt1.isSelected()){
                sq12 = "High Blood Pressure ";
            } else if (q12opt2.isSelected()){
                sq12 = sq12 + "Low Blood Pressure ";
            } else if (q12opt3.isSelected()){
                sq12 = sq12 + "Epileps / Convulsion ";
            } else if (q12opt4.isSelected()){
                sq12 = sq12 + "AIDS / HIV ";
            } else if (q12opt5.isSelected()){
                sq12 = sq12 + "Sexually Transmitted Disease ";
            } else if (q12opt6.isSelected()){
                sq12 = sq12 + "Stomach Troubles / Ulcer ";
            } else if (q12opt7.isSelected()){
                sq12 = sq12 + "Fainting Seizures ";
            } else if (q12opt8.isSelected()){
                sq12 = sq12 + "Rapid Weight Loss ";
            } else if(q12opt9.isSelected()){
                sq12 = sq12 + "Radiation Theraphy ";
            } else if (q12opt10.isSelected()){
                sq12 = sq12 + "Joint Replacement / Implant ";
            } else if (q12opt11.isSelected()){
                sq12 = sq12 + "Heart Disease ";
            } else if (q12opt12.isSelected()){
                sq12 = sq12 + "Hepatitis ";
            } else if (q12opt13.isSelected()){
                sq12 = sq12 + "Cancer / Tumors ";
            } else if (q12opt14.isSelected()){
                sq12 = sq12 + "Asthma ";
            } else if (q12opt15.isSelected()){
                sq12 = sq12 + "Heart Attacks";
            }
            
            mc = new MedicalCond(q1ans, q2ansTF, q3ansTF, q4ansTF, q5ansTF, q6ans, q7ans, q8ans, q9ans,bloodType, bloodPressure, q10ans, sq11, sq12);
            
            
            updateDatabase();
            
            tb.dispose();
        }else{
            if(!hasAnswer(q1)){q1Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));}
            if(!hasAnswer(q2)){q2Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));}
            if(!hasAnswer(q3)){q3Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));}
            if(!hasAnswer(q4)){q4Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));}
            if(!hasAnswer(q5)){q5Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));}
            if(!hasAnswer(q6)){q6Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));}
            if(!hasAnswer(q7)){q7Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));}
            if(!hasAnswer(q8)){q8Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));}
            if(!hasAnswer(q9)){q9Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));}
            if(!hasAnswer(q10)){q10Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));}
            if(hasLetters(bloodPressureTF.getText())){bloodPressureTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));}
            
            JOptionPane.showMessageDialog(null,"One or more fields are invalid. Please recheck inputs.");
        }
    }//GEN-LAST:event_finishButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        tb.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog tb = new JDialog();
                tb.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
                AdditionalInformation adi = null;
                System.out.println("here");
                try{
                    if(ai.getReason().isEmpty()){
                        
                    } else {
                        adi = new AdditionalInformation(tb, pi, ai, mc);
                    }
                }catch(Exception e){
                    adi = new AdditionalInformation(tb, pi);
                }                
                tb.setSize(adi.getPreferredSize());
                System.out.println(adi.isVisible());
                tb.add(adi);
                tb.pack();
                tb.setVisible(true);
                tb.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                }
            }
        );
        tb.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public boolean entriesValid() { 
        if(hasAnswer(q1) &&
           hasAnswer(q2) && 
           hasAnswer(q3) &&
           hasAnswer(q4) && 
           hasAnswer(q5) && 
           hasAnswer(q6) && 
           hasAnswer(q7) && 
           hasAnswer(q8) && 
           hasAnswer(q9) && 
           hasAnswer(q10) &&
           !hasNumbers(bloodTypeCB.getSelectedItem().toString()) &&
           !hasLetters(bloodPressureTF.getText())){
           
           // All entries are valid
           return true; 
        }else{
            // On or more entries are NOT valid
            return false; 
        }
    }
    
    public void grayTFBorders() {
        q1Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201,201,201)));
        q2Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201,201,201)));
        q3Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201,201,201)));
        q4Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201,201,201)));
        q5Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201,201,201)));
        q6Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201,201,201)));
        q7Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201,201,201)));
        q8Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201,201,201)));
        q9Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201,201,201)));
        q10Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201,201,201)));
    }
    
    public boolean hasAnswer(ButtonGroup btnGrp) {
        if(btnGrp.isSelected(null)) {
            // No radio button within the button group is selected
            return false;
        }else{
            return true;
        }
        
    }
    
    public boolean hasNumbers(String numberlessString) {
        String pattern = "[0-9]";
        if(Pattern.compile(pattern).matcher(numberlessString).find()) {
            // There is a number in the string
            return true;
        }else{
            // The string has no numbers
            return false;
        }
    }
    
    public boolean hasLetters(String letterlessString) {
        String pattern = "[A-Za-z]";
        if(Pattern.compile(pattern).matcher(letterlessString).find()) {
            // There is a letter on the string
            return true;
        }else{
            return false;
        }   
    }
    
    public String getAnswer(ButtonGroup btnGrp) {
        if(btnGrp.getSelection().getActionCommand() == "y") {
            return "Yes";
        }else{
            return "No";
        }
    }

    public void updateDatabase() {
       int personalID = pi.UpdatePersonalInfo();
       ai.UpdateAdditionalInfo(personalID);
       mc.Update(personalID);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodPressureTF;
    private javax.swing.JComboBox bloodTypeCB;
    private javax.swing.JButton finishButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup q1;
    private javax.swing.ButtonGroup q10;
    private javax.swing.JLabel q10Label;
    private javax.swing.JRadioButton q10No;
    private javax.swing.JRadioButton q10Yes;
    private javax.swing.JCheckBox q11CB1;
    private javax.swing.JCheckBox q11CB2;
    private javax.swing.JCheckBox q11CB3;
    private javax.swing.JCheckBox q11CB4;
    private javax.swing.JTextField q11CB4TF;
    private javax.swing.JCheckBox q12opt1;
    private javax.swing.JCheckBox q12opt10;
    private javax.swing.JCheckBox q12opt11;
    private javax.swing.JCheckBox q12opt12;
    private javax.swing.JCheckBox q12opt13;
    private javax.swing.JCheckBox q12opt14;
    private javax.swing.JCheckBox q12opt15;
    private javax.swing.JCheckBox q12opt2;
    private javax.swing.JCheckBox q12opt3;
    private javax.swing.JCheckBox q12opt4;
    private javax.swing.JCheckBox q12opt5;
    private javax.swing.JCheckBox q12opt6;
    private javax.swing.JCheckBox q12opt7;
    private javax.swing.JCheckBox q12opt8;
    private javax.swing.JCheckBox q12opt9;
    private javax.swing.JLabel q1Label;
    private javax.swing.JRadioButton q1No;
    private javax.swing.JRadioButton q1Yes;
    private javax.swing.ButtonGroup q2;
    private javax.swing.JLabel q2Label;
    private javax.swing.JRadioButton q2No;
    private javax.swing.JRadioButton q2Yes;
    private javax.swing.JTextField q2YesTF;
    private javax.swing.ButtonGroup q3;
    private javax.swing.JLabel q3Label;
    private javax.swing.JRadioButton q3No;
    private javax.swing.JRadioButton q3Yes;
    private javax.swing.JTextField q3YesTF;
    private javax.swing.ButtonGroup q4;
    private javax.swing.JLabel q4Label;
    private javax.swing.JRadioButton q4No;
    private javax.swing.JRadioButton q4Yes;
    private javax.swing.JTextField q4YesTF;
    private javax.swing.ButtonGroup q5;
    private javax.swing.JLabel q5Label;
    private javax.swing.JRadioButton q5No;
    private javax.swing.JRadioButton q5Yes;
    private javax.swing.JTextField q5YesTF;
    private javax.swing.ButtonGroup q6;
    private javax.swing.JLabel q6Label;
    private javax.swing.JRadioButton q6No;
    private javax.swing.JRadioButton q6Yes;
    private javax.swing.ButtonGroup q7;
    private javax.swing.JLabel q7Label;
    private javax.swing.JRadioButton q7No;
    private javax.swing.JRadioButton q7Yes;
    private javax.swing.ButtonGroup q8;
    private javax.swing.JLabel q8Label;
    private javax.swing.JRadioButton q8No;
    private javax.swing.JRadioButton q8Yes;
    private javax.swing.ButtonGroup q9;
    private javax.swing.JLabel q9Label;
    private javax.swing.JRadioButton q9No;
    private javax.swing.JRadioButton q9Yes;
    // End of variables declaration//GEN-END:variables
}
