/*
 * Copyright (c) 2014, 2015, Project Toothbytes. All rights reserved.
 *
 *
*/
package window;

import java.awt.Toolkit;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 * <h1>About</h1>
 * The {@code About} class implements a program that shows the information 
 * about the program Toothbytes when the user choosed the Help option on the 
 * menu bar and clicked About.
 */
public class About extends javax.swing.JDialog {
    
    /**
     * This constructor creates new form About.
     * @param   parent
     *          Object representation of java.awt.Frame.
     * @param   modal
     *          A boolean representation.
     */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.pack();
        this.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width)/2 - getWidth()/2, (Toolkit.getDefaultToolkit().getScreenSize().height)/2 - getHeight()/2);
    }

    /**
     * This constructor creates new form About without java.awt.Frame parent 
     * and boolean modal.
     */
    public About() {
        super();
        initComponents();
        this.setVisible(true);
        this.pack();
        this.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width)/2 - getWidth()/2, (Toolkit.getDefaultToolkit().getScreenSize().height)/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        moreTA = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        developersTP = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        aboutTP = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        developersTP1 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        developersTP2 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        aboutPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("res/icons/about_logo.png"));

        moreTA.setEditable(false);
        moreTA.setColumns(20);
        moreTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        moreTA.setLineWrap(true);
        moreTA.setRows(5);
        moreTA.setWrapStyleWord(true);
        jScrollPane2.setViewportView(moreTA);
        moreTA.setText("Java: " + System.getProperty("java.runtime.version")
            + System.getProperty("path.separator") + " "
            + System.getProperty("java.vm.name") + " "
            + System.getProperty("java.vm.version") + "\n"
            + "Runtime: " + System.getProperty("java.runtime.name")
            + " " + System.getProperty("java.vm.version") + "\n"
            + "System: " + System.getProperty("os.name") + " "
            + System.getProperty("os.version") + " running on "
            + System.getProperty("sun.cpu.isalist") + "; "
            + System.getProperty("sun.jnu.encoding") + "; "
            + System.getProperty("user.country") + "\n"
            + "User Directory: " + System.getProperty("user.dir"));

        // + "\n" + "Class Directory: " + System.getProperty("java.class.path")

        jScrollPane4.setBorder(null);

        developersTP.setEditable(false);
        developersTP.setBorder(null);
        developersTP.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        developersTP.setText("Louriz Bringas\nNichole Joanne Fabian\nVilgladys Maglaya\nYumi Takuma");
        jScrollPane4.setViewportView(developersTP);
        StyledDocument dtp = developersTP.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        dtp.setParagraphAttributes(0, dtp.getLength(), center, false);

        jScrollPane3.setBorder(null);

        aboutTP.setEditable(false);
        aboutTP.setBorder(null);
        aboutTP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        aboutTP.setText("Toothbytes is a dental management software exclusively only for Dr. Ruben Pascual Dental Clinic. This software helps with the organization of the patients’ personal and dental records which includes the management of the billing records and the appointment scheduling. For more information, please visit Pines City Doctors' Hospital, Baguio City, Benguet, Philippines.");
        jScrollPane3.setViewportView(aboutTP);
        StyledDocument aboutDoc = aboutTP.getStyledDocument();
        SimpleAttributeSet justify = new SimpleAttributeSet();
        StyleConstants.setAlignment(justify, StyleConstants.ALIGN_JUSTIFIED);
        aboutDoc.setParagraphAttributes(0, aboutDoc.getLength(), justify, false);

        jScrollPane5.setBorder(null);

        developersTP1.setEditable(false);
        developersTP1.setBorder(null);
        developersTP1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        developersTP1.setText("Emrod Van Gonzales\nJheraldine Bugtong\nJolas Burayag\nKimwell Tandoc");
        jScrollPane5.setViewportView(developersTP1);
        StyledDocument dtp1 = developersTP1.getStyledDocument();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        dtp1.setParagraphAttributes(0, dtp1.getLength(), center, false);

        jScrollPane6.setBorder(null);

        developersTP2.setEditable(false);
        developersTP2.setBorder(null);
        developersTP2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        developersTP2.setText("Developers:");
        jScrollPane6.setViewportView(developersTP2);
        StyledDocument dtp2 = developersTP2.getStyledDocument();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        dtp2.setParagraphAttributes(0, dtp2.getLength(), center, false);

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                About dialog = new About(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JTextPane aboutTP;
    private javax.swing.JTextPane developersTP;
    private javax.swing.JTextPane developersTP1;
    private javax.swing.JTextPane developersTP2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea moreTA;
    // End of variables declaration//GEN-END:variables
}
