/*
 * Copyright (c) 2014, 2015, Project Toothbytes. All rights reserved.
 *
 *
*/
package components;

import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JDialog;
import models.RecordsX;
import utilities.DBAccess;
import models.Appointment;
import window.forms.MiniBilling;

public class PaymentSchedule extends javax.swing.JPanel {

    /**
     * Creates new form PaymentSchedule
     */
        
    private Appointment appointment;
    private ArrayList<RecordsX> recordsX;
    
    public PaymentSchedule(Appointment appointment) {
        initComponents();
        this.appointment = appointment;
        recordsX = DBAccess.getRecordsData(appointment.getPatientID());
        setInformation();
    }
    
    private void setInformation(){
        DecimalFormat df = new DecimalFormat("#,###.00");
        NameLabel.setText(DBAccess.getPatientName(appointment.getPatientID()));
        DateLabel.setText(appointment.getAppointmentDate());
        TimeLabel.setText(appointment.getAppointmentTime());
        AmountLabel.setText("P " + String.valueOf(df.format(totalBalance())));
    }
    
    private double totalBalance(){
        double total = 0;
        
        for(int i = 0; i < recordsX.size(); i++){
            total = total + recordsX.get(i).getBalance();
        }
        
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jButton3.setText("Finish");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        NameLabel.setText("Name");

        TimeLabel.setText("Time");

        AmountLabel.setText("Remaining Balance");

        DateLabel.setText("Date");

        jButton4.setText("Pay");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TimeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NameLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AmountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameLabel)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel)
                    .addComponent(TimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountLabel)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                JDialog mb = new JDialog();
                MiniBilling miniBill = new MiniBilling(mb, appointment.getPatientID());
                
                mb.setSize(miniBill.getPreferredSize());
                mb.add(miniBill);
                mb.pack();
                mb.setVisible(true);
                mb.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            }
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
